spring.application.name=NextStep

spring.datasource.url=jdbc:postgresql://localhost:5432/sobrietydb
spring.datasource.username=postgres
spring.datasource.password=innebandy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
logging.level.org.springframework.ai=DEBUG

